---
driver_plugin: vagrant

driver_config:
  require_chef_omnibus: 11.10.4

platforms:
  - name: ubuntu-13.10
    run_list:
      - recipe[apt]
  - name: ubuntu-12.10
      run_list:
        - recipe[apt]
  - name: ubuntu-12.04
      run_list:
        - recipe[apt]
  - name: ubuntu-10.04
      run_list:
        - recipe[apt]
  - name: centos-6.4
    run_list:
      - recipe[yum::epel]

suites:
  - name: default
    run_list:
      - recipe[znc]
    attributes: {}
